### ISSUE TITLE
Will not install under macOS (Python 3.8)

### ISSUE THREAD

**Issue by lemire** [quantopian/libpy#192]
```
$ pip3 install libpy
Collecting libpy
  Using cached libpy-0.2.3.tar.gz (177 kB)
Collecting numpy
  Downloading numpy-1.19.0-cp38-cp38-macosx_10_9_x86_64.whl (15.3 MB)
     |████████████████████████████████| 15.3 MB 1.8 MB/s
Using legacy setup.py install for libpy, since package 'wheel' is not installed.
Installing collected packages: numpy, libpy
    Running setup.py install for libpy ... error
    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/y8/nl_pprtd12x78vqkv3px0bp40000gn/T/pip-install-_7wi4bps/libpy/setup.py'"'"'; __file__='"'"'/private/var/folders/y8/nl_pprtd12x78vqkv3px0bp40000gn/T/pip-install-_7wi4bps/libpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/y8/nl_pprtd12x78vqkv3px0bp40000gn/T/pip-record-ndq50v_2/install-record.txt --single-version-externally-managed --compile --install-headers /Library/Frameworks/Python.framework/Versions/3.8/include/python3.8/libpy
         cwd: /private/var/folders/y8/nl_pprtd12x78vqkv3px0bp40000gn/T/pip-install-_7wi4bps/libpy/
    Complete output (95 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/libpy
    copying libpy/build.py -> build/lib/libpy
    copying libpy/__init__.py -> build/lib/libpy
    creating build/lib/libpy/include
    creating build/lib/libpy/include/libpy
    copying libpy/include/libpy/autofunction.h -> build/lib/libpy/include/libpy
    copying libpy/include/libpy/borrowed_ref.h -> build/lib/libpy/include/libpy
    copying libpy/include/libpy/range.h -> build/lib/libpy/include/libpy
    copying libpy/include/libpy/numpy_utils.h -> build/lib/libpy/include/libpy
    copying libpy/include/libpy/call_function.h -> build/lib/libpy/include/libpy
    copying libpy/include/libpy/itertools.h -> build/lib/libpy/include/libpy
    copying libpy/include/libpy/devirtualize.h -> build/lib/libpy/include/libpy
    copying libpy/include/libpy/demangle.h -> build/lib/libpy/include/libpy
    copying libpy/include/libpy/scope_guard.h -> build/lib/libpy/include/libpy
    copying libpy/include/libpy/gil.h -> build/lib/libpy/include/libpy
    copying libpy/include/libpy/to_object.h -> build/lib/libpy/include/libpy
    copying libpy/include/libpy/any_vector.h -> build/lib/libpy/include/libpy
    copying libpy/include/libpy/stream.h -> build/lib/libpy/include/libpy
    copying libpy/include/libpy/char_sequence.h -> build/lib/libpy/include/libpy
    copying libpy/include/libpy/dict_range.h -> build/lib/libpy/include/libpy
    copying libpy/include/libpy/build_tuple.h -> build/lib/libpy/include/libpy
    copying libpy/include/libpy/str_convert.h -> build/lib/libpy/include/libpy
    copying libpy/include/libpy/table_details.h -> build/lib/libpy/include/libpy
    copying libpy/include/libpy/buffer.h -> build/lib/libpy/include/libpy
    copying libpy/include/libpy/datetime64.h -> build/lib/libpy/include/libpy
    copying libpy/include/libpy/getattr.h -> build/lib/libpy/include/libpy
    copying libpy/include/libpy/owned_ref.h -> build/lib/libpy/include/libpy
    copying libpy/include/libpy/util.h -> build/lib/libpy/include/libpy
    copying libpy/include/libpy/table.h -> build/lib/libpy/include/libpy
    copying libpy/include/libpy/automodule.h -> build/lib/libpy/include/libpy
    copying libpy/include/libpy/from_object.h -> build/lib/libpy/include/libpy
    copying libpy/include/libpy/abi.h -> build/lib/libpy/include/libpy
    copying libpy/include/libpy/meta.h -> build/lib/libpy/include/libpy
    copying libpy/include/libpy/object_map_key.h -> build/lib/libpy/include/libpy
    copying libpy/include/libpy/exception.h -> build/lib/libpy/include/libpy
    copying libpy/include/libpy/any.h -> build/lib/libpy/include/libpy
    copying libpy/include/libpy/hash.h -> build/lib/libpy/include/libpy
    copying libpy/include/libpy/autoclass.h -> build/lib/libpy/include/libpy
    copying libpy/include/libpy/singletons.h -> build/lib/libpy/include/libpy
    copying libpy/include/libpy/ndarray_view.h -> build/lib/libpy/include/libpy
    creating build/lib/libpy/include/libpy/detail
    copying libpy/include/libpy/detail/numpy.h -> build/lib/libpy/include/libpy/detail
    copying libpy/include/libpy/detail/autoclass_object.h -> build/lib/libpy/include/libpy/detail
    copying libpy/include/libpy/detail/no_destruct_wrapper.h -> build/lib/libpy/include/libpy/detail
    copying libpy/include/libpy/detail/api.h -> build/lib/libpy/include/libpy/detail
    copying libpy/include/libpy/detail/autoclass_cache.h -> build/lib/libpy/include/libpy/detail
    copying libpy/include/libpy/detail/python.h -> build/lib/libpy/include/libpy/detail
    copying libpy/_build-and-run -> build/lib/libpy
    copying libpy/_detect-compiler.cc -> build/lib/libpy
    c++ -std=gnu++17 -g -O3 -fwrapv -fno-strict-aliasing -pipe -march=x86-64 -mtune=generic -fvisibility=hidden -Werror -Wall -Wextra -Wno-register -Wno-missing-field-initializers -Wsign-compare -Wparentheses -Wno-gnu-string-literal-operator-template -Wno-missing-braces -Wno-self-assign-overloaded -DPY_MAJOR_VERSION=2 -DPY_MINOR_VERSION=7 -DLIBPY_MAJOR_VERSION=0 -DLIBPY_MINOR_VERSION=2 -DLIBPY_MICRO_VERSION=3 -ferror-limit=5 -flto  -Iinclude/  -I/Library/Frameworks/Python.framework/Versions/2.7/include  -I/Library/Frameworks/Python.framework/Versions/2.7/include  -I/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7  -I/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7  -I/Users/lemire/Library/Python/2.7/lib/python/site-packages/numpy/core/include -MD -fPIC -c src/abi.cc -o src/abi.o
    In file included from src/abi.cc:1:
    In file included from include/libpy/abi.h:4:
    In file included from include/libpy/exception.h:13:
    include/libpy/util.h:58:12: error: use of undeclared identifier 'PyUnicode_AsUTF8'
        return PyUnicode_AsUTF8(ob.get());
               ^
    include/libpy/util.h:71:10: error: use of undeclared identifier 'PyUnicode_AsUTF8AndSize'
        cs = PyUnicode_AsUTF8AndSize(ob.get(), &size);
             ^
    2 errors generated.
    make: *** [src/abi.o] Error 1
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/y8/nl_pprtd12x78vqkv3px0bp40000gn/T/pip-install-_7wi4bps/libpy/setup.py", line 49, in <module>
        setup(
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/y8/nl_pprtd12x78vqkv3px0bp40000gn/T/pip-install-_7wi4bps/libpy/setup.py", line 36, in run
        raise BuildFailed(
    __main__.BuildFailed: Command 'make -C "/private/var/folders/y8/nl_pprtd12x78vqkv3px0bp40000gn/T/pip-install-_7wi4bps/libpy" libpy/libpy.so' failed with code 512
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/y8/nl_pprtd12x78vqkv3px0bp40000gn/T/pip-install-_7wi4bps/libpy/setup.py'"'"'; __file__='"'"'/private/var/folders/y8/nl_pprtd12x78vqkv3px0bp40000gn/T/pip-install-_7wi4bps/libpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/y8/nl_pprtd12x78vqkv3px0bp40000gn/T/pip-record-ndq50v_2/install-record.txt --single-version-externally-managed --compile --install-headers /Library/Frameworks/Python.framework/Versions/3.8/include/python3.8/libpy Check the logs for full command output.
```

**Comment by gerrymanoim** [comment]
Same as https://github.com/quantopian/libpy/issues/191#issuecomment-659483418. 

Could you please check the output of which python and python --version in your environment? Depending on how your environments are configured, you may need to run PYTHON=python3 pip3 install libpy .

**Comment by lemire** [comment]
`PYTHON=python3 pip3 install libpy` solves the issue.
