### ISSUE TITLE
Will not install under macOS (Python 2.7)

### ISSUE THREAD

**Issue by lemire** [quantopian/libpy#193]
```
$ pip install libpy
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting libpy
  Using cached libpy-0.2.3.tar.gz (177 kB)
Requirement already satisfied: numpy in /Users/lemire/Library/Python/2.7/lib/python/site-packages (from libpy) (1.16.6)
Building wheels for collected packages: libpy
  Building wheel for libpy (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/y8/nl_pprtd12x78vqkv3px0bp40000gn/T/pip-install-b7O1uA/libpy/setup.py'"'"'; __file__='"'"'/private/var/folders/y8/nl_pprtd12x78vqkv3px0bp40000gn/T/pip-install-b7O1uA/libpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/y8/nl_pprtd12x78vqkv3px0bp40000gn/T/pip-wheel-kMoG_U
       cwd: /private/var/folders/y8/nl_pprtd12x78vqkv3px0bp40000gn/T/pip-install-b7O1uA/libpy/
  Complete output (30 lines):
  running bdist_wheel
  running build
  running build_py
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/y8/nl_pprtd12x78vqkv3px0bp40000gn/T/pip-install-b7O1uA/libpy/setup.py", line 84, in <module>
      '_detect-compiler.cc',
    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build.py", line 127, in run
      self.run_command(cmd_name)
    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/private/var/folders/y8/nl_pprtd12x78vqkv3px0bp40000gn/T/pip-install-b7O1uA/libpy/setup.py", line 31, in run
      super().run()
  TypeError: super() takes at least 1 argument (0 given)
  ----------------------------------------
  ERROR: Failed building wheel for libpy
  Running setup.py clean for libpy
Failed to build libpy
Installing collected packages: libpy
    Running setup.py install for libpy ... error
    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/y8/nl_pprtd12x78vqkv3px0bp40000gn/T/pip-install-b7O1uA/libpy/setup.py'"'"'; __file__='"'"'/private/var/folders/y8/nl_pprtd12x78vqkv3px0bp40000gn/T/pip-install-b7O1uA/libpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/y8/nl_pprtd12x78vqkv3px0bp40000gn/T/pip-record-Q92UTu/install-record.txt --single-version-externally-managed --compile --install-headers /Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/libpy
         cwd: /private/var/folders/y8/nl_pprtd12x78vqkv3px0bp40000gn/T/pip-install-b7O1uA/libpy/
    Complete output (32 lines):
    running install
    running build
    running build_py
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/y8/nl_pprtd12x78vqkv3px0bp40000gn/T/pip-install-b7O1uA/libpy/setup.py", line 84, in <module>
        '_detect-compiler.cc',
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install.py", line 563, in run
        self.run_command('build')
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build.py", line 127, in run
        self.run_command(cmd_name)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/private/var/folders/y8/nl_pprtd12x78vqkv3px0bp40000gn/T/pip-install-b7O1uA/libpy/setup.py", line 31, in run
        super().run()
    TypeError: super() takes at least 1 argument (0 given)
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/y8/nl_pprtd12x78vqkv3px0bp40000gn/T/pip-install-b7O1uA/libpy/setup.py'"'"'; __file__='"'"'/private/var/folders/y8/nl_pprtd12x78vqkv3px0bp40000gn/T/pip-install-b7O1uA/libpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/y8/nl_pprtd12x78vqkv3px0bp40000gn/T/pip-record-Q92UTu/install-record.txt --single-version-externally-managed --compile --install-headers /Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/libpy Check the logs for full command output.
```

**Comment by gerrymanoim** [comment]
Apologies - we no longer support py27.
